[build]
  publish = "build"
command = "yarn build"
  functions = "functions"

  [functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["import-fresh"]

# Rewrite API requests to actual location of serverless functions
[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Catch all other requests that don't match a file
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200