[build]
  publish = "build"
command = "yarn build"
  functions = "functions"

  [functions]
  included_files = ["src/functions/**/*"]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["import-fresh"]